name: Frontend Tests

on:
  push:
    branches: [main, dev-Ahian]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"
          channel: "stable"

      - name: Instalar dependencias
        run: flutter pub get

      - name: Analizar código estático
        run: flutter analyze

      - name: Ejecutar pruebas unitarias
        run: flutter test
